services:
  postgres-estoque:
    image: postgres:latest
    container_name: postgres-estoque
    environment:
      POSTGRES_USER: estoque_user
      POSTGRES_PASSWORD: estoque_password
      POSTGRES_DB: estoque_db
    ports:
      - "5434:5432"
    volumes:
      - postgres-estoque-data:/var/lib/postgresql/data

  estoque:
    build:
      context: .
    container_name: estoque
    depends_on:
      - postgres-estoque
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-estoque:5432/estoque_db
      SPRING_DATASOURCE_USERNAME: estoque_user
      SPRING_DATASOURCE_PASSWORD: estoque_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8092"

volumes:
  postgres-estoque-data:
