name: CI/CD para Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images for all services
        run: |
          docker-compose build

      - name: Start Docker Compose services
        run: |
          docker-compose up -d
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: Run integration tests
        run: |
          curl --retry 10 --retry-delay 5 -f http://localhost:8081/actuator/health
          curl --retry 10 --retry-delay 5 -f http://localhost:8082/actuator/health
          curl --retry 10 --retry-delay 5 -f http://localhost:8083/actuator/health

      - name: Stop Docker Compose services
        if: always()
        run: |
          docker-compose down
