name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and Test Cliente
        working-directory: ./cliente
        run: |
          mvn clean package

      - name: Build and Test Estoque
        working-directory: ./estoque
        run: |
          mvn clean package

      - name: Build and Test Pedido
        working-directory: ./pedido
        run: |
          mvn clean package

      - name: Start Docker Compose
        run: docker-compose up --build -d

      - name: Stop Docker Compose
        run: docker-compose down
